### ISSUE TITLE
Projetkwebseite

### ISSUE THREAD

**Issue by Kreunus** [Kreunus/vrForFuture#29]
**Deadline: 24.06.2020**
Webseite zum Projekt

- Favicon, Title: vrForFuture
- Header: Logo, Navigation
- Body: Home, Team, Preview (Hunters Path)
- Footer: Copyright, Datenschutz, Impressum

**Comment by martinchristians** [comment]
Done ;)

**Comment by Kreunus** [comment]
Look nice but, we don't close issues by ourself -> preview at monday

+ Smothscroll is still missing
